### ISSUE TITLE
Can the Lv 170 / 180 weapon being added?

### ISSUE THREAD

**Issue by HikariCalyx** [kdo9921/Starforce-Simulation#3]
Hi, I made a fork based on your simulator and modified it into the version for CMS (MapleStory China 冒险岛Online) because the success rate is completely different from other regions, including KMS, GMS.
https://github.com/HikariCalyx/Starforce-Simulation-CMS

When I try to add the Lv 170 / 180 weapon (Lazuli/Lapis Type 7/8 for Zero), I found Lv 200 weapon will become into Lazuli/Lapis Type 7.
Any idea?

**Comment by kdo9921** [comment]
HI, KMS does not have 170 or 180 level equipment, so the 7th index is set to 200 level. 
I recommend edit **45 line** in **levelApply()** function

KMS : levelIndex = level / 10 == 20 ? 7 : level / 10 - 10; //200제 장비 때문에 한짓 
CMS : levelIndex = level / 10 == 20 ? 9 : level / 10 - 10;
